### ISSUE TITLE
The missing W :-) (very small "bug" IMHO)

### ISSUE THREAD

**Issue by fft1010** [Nicxe/esphome#1]
Hi,
many thanks for sharing your weatherman.yaml file. After my journey with trying to install it with mac (don't do it), it worked immediately.
But I noticed a very small glitch I wanted to tell:
In the font declarations the "W" is missing, I saw there A-Z (except W). Only an issue if you are like me german, and try to write
"WARTE AUF DATEN"   (waiting for data)
as the the first change in the code :-)

Again: Many thanks for your code!

One question. I was trying to use the "%", but could not find a way to use it as it seems to be escaped somehow, but I could not find how. 

all the best
Juergen

**Comment by Nicxe** [comment]
Thanks for noticing, I have not used the W in my config so have not seen it until now. 

I am using % as a sign for the percent chance of rain. Just add `'%'`, look at the end of my[ line 121 ](https://github.com/Nicxe/esphome/blob/8fca51657432dbbb338bb21c92295a1d8b1cedf8/weatherman.yaml#L121)

**Comment by Nicxe** [comment]
Added W to the code

**Comment by fft1010** [comment]
Hi @Nicxe ,
I saw it in the font definition, and wanted to use the % for humidity. I tried \% but just learned that I have to escape it like '%%'
thanks
Juergen
